### ISSUE TITLE
Track and resolve technical debt towards MVP

### ISSUE THREAD

**Issue by thesethtruth** [Zenmo/Holon-webapp#175]
### Technical integration:
- [x] ZEnMo/Holon-webapp#248
- [ ] ZEnMo/Holon-webapp#249
- [ ] ZEnMo/Holon-webapp#250

### Preprocessor
- [x] ZEnMo/Holon-webapp#244
- [x] ZEnMo/Holon-webapp#245
- [x] ZEnMo/Holon-webapp#246
- [x] ZEnMo/Holon-webapp#247
- [ ] ZEnMo/Holon-webapp#255

#### Cloudclient
- [x] ZEnMo/Holon-webapp#237
- [x] ZEnMo/Holon-webapp#238
- [x] ZEnMo/Holon-webapp#239
- [ ] ZEnMo/Holon-webapp#240
- [ ] ZEnMo/Holon-webapp#241
- [x] ZEnMo/Holon-webapp#242
- [x] ZEnMo/Holon-webapp#251

#### Economic module
- [x] ZEnMo/Holon-webapp#252
- [ ] ZEnMo/Holon-webapp#253
- [x] ZEnMo/Holon-webapp#254

#### ETM scaling
- [ ] ZEnMo/Holon-webapp#256
- [x] ZEnMo/Holon-webapp#257
- [ ] ZEnMo/HOLON-ETM#16
- [ ] ZEnMo/HOLON-ETM#15
- [ ] ZEnMo/Holon-webapp#260
- [ ] ZEnMo/HOLON-ETM#20
- [ ] ZEnMo/Holon-webapp#262
- [ ] ZEnMo/Holon-webapp#263
- [ ] ZEnMo/Holon-webapp#264
- [x] ZEnMo/Holon-webapp#265
- [ ] ZEnMo/Holon-webapp#266
- [ ] ZEnMo/HOLON-ETM#17

**Comment by thesethtruth** [comment]
@mattijsstam we cannot set values separate of labels; that might be a problem
![image](https://user-images.githubusercontent.com/78690362/204504212-a0203494-c635-4fe0-968f-aae7a256887e.png)

**Comment by thesethtruth** [comment]
@mattijsstam how do we use the wiki modals?

**Comment by thesethtruth** [comment]
https://github.com/ZEnMo/HOLON-cloudclient/issues/17
