### ISSUE TITLE
Todo's afronding industrie en agro casus

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#935]
- [ ] drie taalfouten eruit halen
- [ ] industrie: negatieve zelfvoorzienendheid checken
- [ ] agro: impact van zon en wind sliders is praktisch nul, maar zon op dak is hoog
